"""update id fo uuid

Revision ID: 08f685dfe80a
Revises: 1f931773dba4
Create Date: 2022-08-30 14:48:58.888618

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '08f685dfe80a'
down_revision = '1f931773dba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
