"""add name

Revision ID: 1e83ddb30136
Revises: 4207c517362c
Create Date: 2022-08-30 23:58:37.886314

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1e83ddb30136'
down_revision = '4207c517362c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
