"""init

Revision ID: 1f931773dba4
Revises:
Create Date: 2022-08-30 14:43:16.061516

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1f931773dba4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_telegram', sa.Integer(), nullable=False),
    sa.Column('data_reg', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('last_auth', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
