"""add sessoin token

Revision ID: 4207c517362c
Revises: 9c2b9d6eb99b
Create Date: 2022-08-30 21:11:55.997295

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4207c517362c'
down_revision = '9c2b9d6eb99b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
