"""add sessoin token

Revision ID: 9c2b9d6eb99b
Revises: faa9c4c50cb3
Create Date: 2022-08-30 21:10:17.791300

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9c2b9d6eb99b'
down_revision = 'faa9c4c50cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
