"""add sessoin token

Revision ID: c3ba2c97a5c1
Revises: f9dd884c592c
Create Date: 2022-08-30 20:39:52.282149

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c3ba2c97a5c1'
down_revision = 'f9dd884c592c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('session_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'session_token')
    # ### end Alembic commands ###
