"""update id fo uuid to

Revision ID: f9dd884c592c
Revises: 08f685dfe80a
Create Date: 2022-08-30 14:51:34.297342

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f9dd884c592c'
down_revision = '08f685dfe80a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
