"""add sessoin token

Revision ID: faa9c4c50cb3
Revises: c3ba2c97a5c1
Create Date: 2022-08-30 20:59:18.188942

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'faa9c4c50cb3'
down_revision = 'c3ba2c97a5c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
